version: '3.7'

services:
  api:
    build:
      context: ./api
    networks:
      - simple_app
      
  web:
    build:
      context: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - simple_app
    ports:
      - 80:80

networks:
  simple_app: